name: bmd_flutter_tools
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.0-162.1.beta
  # sdk: '>=3.3.2 <4.0.0'




# ======================================================================================================================
# MARK: Dependencies
# -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
dependencies:
    flutter:
        sdk: flutter
    app_links: ^6.4.1
    adaptive_theme: ^3.6.0
    auto_size_text: ^3.0.0
    build_runner: ^2.4.9
    camera: ^0.11.1
    collection: ^1.18.0
    connectivity_plus: ^4.0.0
    country_code_picker: ^3.3.0
    country_picker: ^2.0.27
    crypt: ^4.3.1
    crypto: ^3.0.3
    csv: ^5.0.0
    cupertino_icons: ^1.0.6
    device_info_plus: ^10.0.1
    dio: ^5.4.3+1
    expandable: ^5.0.1
    firebase_analytics: ^12.0.2
    firebase_app_installations: ^0.4.0
    firebase_core: ^4.0.0
    firebase_messaging: ^16.0.0
    flex_color_scheme: ^7.3.1
    float_column: ^4.0.1            # Layout widget used on the SeminarInfo widget
    flutter_carousel_widget: ^3.1.0 # Used to display sponsors' logos
    flutter_html: ^3.0.0-beta.2
    flutter_launcher_icons: ^0.13.1
    flutter_local_notifications: ^17.2.2
    flutter_pdfview: 1.3.4          # Used to display PDFs
    flutter_riverpod: ^2.5.1        # Used for app state management
    flutter_secure_storage: ^9.0.0  # Used to persist session data
    flutter_sficon: ^1.1.2          # Provides SF Icons for Flutter
    flutter_svg: ^2.2.0             # Used to display SVGs
    go_router: ^14.2.8              # Used for in-app navigation
    google_fonts: ^6.2.1
    html: any
    http: ^1.2.1
    intl: ^0.19.0
    intl_phone_number_input: ^0.7.5
    json_annotation: ^4.9.0
    json_serializable: ^6.8.0
    kalender: ^0.4.1
    mailer: ^6.1.0
    mobile_scanner: ^7.0.0-beta.6 # Must use at least 7.0.0 for arm64 simulator support
    multi_dropdown: ^3.0.1
    mysql_client: ^0.0.27
    mysql1: ^0.20.0
    oauth2: ^2.0.2
    otp: ^3.0.1
    package_info_plus: ^8.3.1
    path: ^1.9.0
    path_provider: ^2.0.14
    permission_handler: ^12.0.1
    provider: ^6.1.2
    qr: ^3.0.2
    qr_flutter: ^4.1.0
    sentry_flutter: ^9.6.0
    share_plus: ^11.0.0
    shared_preferences: ^2.2.2
    sqflite: ^2.4.0
    string_validator: ^1.1.0      # Used by the BadgeScanner to validate UUIDs
    syncfusion_flutter_signaturepad: ^28.1.41
    toggle_switch: ^2.3.0         # Versatile toggle switch widget used throughout the app
    universal_io: ^2.2.2          # Cross-platform dart:io
    url_launcher: ^6.2.5          # Launches URLs internally/externally
    uuid: ^4.4.0                  # Used to generate UUIDs locally
    validation_chain: ^0.0.11
    webview_flutter: ^4.13.0      # Used on RemoteHtmlWebView
    wordpress_client: ^8.4.1




# ======================================================================================================================
# MARK: Dev Dependencies
# -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
dev_dependencies:
    flutter_test:
        sdk: flutter
    integration_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    test: ^1.25.15
    pointycastle: ^3.7.3




# ======================================================================================================================
# MARK: Assets
# -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
flutter:
    uses-material-design: true

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # MARK: Assets
    # -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
    assets:
        - assets/images/ad--keynotes-and-seminars--001.jpg
        - assets/images/ad-lead-retrieval-features.png
        - assets/images/build-expo-usa-icon.png
        - assets/images/build-expo-usa-icon-android.png
        - assets/images/build-expo-usa-icon-ios.png
        - assets/images/build-expo-usa-logo-horizontal.png
        - assets/images/build-expo-usa-logo-splash.png
        - assets/images/build-expo-usa-logo-splash-android.png
        - assets/images/build-expo-usa-logo-vertical.png
        - assets/images/icon--keynotes-and-seminars--001.png
        - assets/images/icon--exhibitor-resources--badge.png
        - assets/images/icon--exhibitor-resources--chart.png
        - assets/images/icon--exhibitor-resources--checklist.png
        - assets/images/icon--exhibitor-resources--document.png
        - assets/images/icon--exhibitor-resources--flyer.png
        - assets/images/icon--exhibitor-resources--mail.png
        - assets/images/icon--exhibitor-resources--photo.png
        - assets/images/icon--exhibitor-resources--social.png
        - assets/images/icon--exhibitor-resources--ticket.png
        - assets/images/texture__button_noise_highlight.png
        - assets/images/texture__button_noise_shadow.png
        - assets/images/placeholder--company-logo.png
        - assets/images/placeholder--user-profile-picture.png
        - assets/images/sample--construction-monthly-cover.jpg
        - assets/images/show-banner-placeholder.png
        - assets/images/sponsor-logo--alltek-construction.png
        - assets/images/sponsor-logo--build-expo-usa.png
        - assets/images/sponsor-logo--construction-monthly.png
        - assets/images/showroom-floor.jpg

        - assets/pdfs/ad-lead-retrieval-features-001.pdf
        - assets/pdfs/booth-photos--2025-001.pdf
        - assets/pdfs/construction-monthly--2025-austin-001.pdf
        - assets/pdfs/exhibitor-planner-001.pdf
        - assets/pdfs/floor-plan--2025-austin-001.pdf
        - assets/pdfs/media-kit-2024-charlotte-001.pdf


    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    # MARK: Fonts
    # -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -   -
    fonts:
        - family: oswaldstencil
          fonts:
            - asset: assets/fonts/Oswald-Stencil.ttf
        - family: fashionista
          fonts:
            - asset: assets/fonts/fashionista.ttf
        - family: tungsten
          fonts:
            - asset: assets/fonts/Tungsten-Bold.ttf
        - family: lato
          fonts:
            - asset: assets/fonts/Lato-Regular.ttf
            - asset: assets/fonts/Lato-Bold.ttf
              weight: 500
            - asset: assets/fonts/Lato-BoldItalic.ttf
              style: italic
              weight: 700
            - asset: assets/fonts/Lato-Light.ttf
              weight: 300
            - asset: assets/fonts/Lato-Hairline.ttf
              weight: 200
            - asset: assets/fonts/Lato-HairlineItalic.ttf
              style: italic
              weight: 200
            - asset: assets/fonts/Lato-Black.ttf
              weight: 600
            - asset: assets/fonts/Lato-Italic.ttf
              style: italic
            - asset: assets/fonts/Lato-BlackItalic.ttf
              style: italic
              weight: 700
            - asset: assets/fonts/Lato-LightItalic.ttf
              style: italic
              weight: 400




# ======================================================================================================================
# MARK: Splash Screen
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
flutter_native_splash:

    color: "#FFFFFF"
    image: "assets/images/build-expo-usa-logo-splash.png"
    android_12:
        image: "assets/images/build-expo-usa-logo-splash-android.png"
        image_dark: "assets/images/build-expo-usa-logo-splash-android.png"
        icon_background_color: "#FFFFFF"
        icon_background_color_dark: "#FFFFFF"




# ======================================================================================================================
# MARK: App Icons
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
flutter_launcher_icons:
    image_path: "assets/images/build-expo-usa-icon.png"

    android: true
    image_path_android: "assets/images/build-expo-usa-icon-android.png"
    min_sdk_android: 23 # android min sdk min:16, default 21
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/images/build-expo-usa-icon-android.png"
    adaptive_icon_foreground_inset: 28
    # adaptive_icon_monochrome: "assets/icon/monochrome.png"

    ios: true
    image_path_ios: "assets/images/build-expo-usa-icon-ios.png"
    remove_alpha_channel_ios: true
    # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
    # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
    # desaturate_tinted_to_grayscale_ios: true

    web:
        generate: true
        background_color: "#FFFFFF"
        theme_color: "#FFFFFF"
        image_path: "assets/images/build-expo-usa-icon.png"

    windows:
        generate: true
        icon_size: 48 # min:48, max:256, default: 48
        image_path: "assets/images/build-expo-usa-icon.png"


    macos:
        generate: true
        image_path: "assets/images/build-expo-usa-icon.png"
