// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADrHRRP0C5iYpJaVtGY9SHd5xmQJdJk_g',
    appId: '1:1060358689884:android:fe85ba40add8ff24aa0299',
    messagingSenderId: '1060358689884',
    projectId: 'icecrm-85086',
    storageBucket: 'icecrm-85086.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADFM4EAnnNRDloTcd9s-63ZO17kIO1Zbc',
    appId: '1:1060358689884:ios:a54a478f1b1915d1aa0299',
    messagingSenderId: '1060358689884',
    projectId: 'icecrm-85086',
    storageBucket: 'icecrm-85086.firebasestorage.app',
    iosBundleId: 'com.icmexpo.bmd_flutter_tools',
  );
}